### ISSUE TITLE
Add context support to utils commands

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astartectl#103]
Allow util commands (eg: `astartectl utils gen-jwt`) to retrieve informations from the config context

**Comment by Annopaolo** [comment]
The `astartectl config contexts` command provides a number of informative sub-commands, e.g. `list`, `show`, `get-realm-key`. The same goes for `astartectl config clusters`, with e.g. `list`, `show`, `get-housekeeping-key`.
