### ISSUE TITLE
Allow retrieving the list of devices that were active since a certain timestamp

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astartectl#118]
The API should look something like this
`astartectl devices list --active-since=2020-11-01`
This is already possible, the client side code should look something like this (assuming `t` as the "since" timestamp):
- Retrieve the detailed devices list
- Filter out all devices that have `connected: false`
- Filter out all devices that have a disconnection < `t`

**Comment by Annopaolo** [comment]
Closed by #120.
