### ISSUE TITLE
Add support for object aggregated Astarte interfaces 

### ISSUE THREAD

**Issue by Pavinati** [astarte-platform/astartectl#154]
`astartectl appengine devices get-samples` fails on object aggregated interfaces with the following error
```
json: cannot unmarshal object into Go value of type []client.DatastreamAggregateValue
```

**Comment by Annopaolo** [comment]
This has been fixed in the `astarte-go` library by [this PR](https://github.com/astarte-platform/astarte-go/pull/24). The issue will be solved when we update the `astarte-go` dependency to a newer (> v0.90.2) version

**Comment by Annopaolo** [comment]
Actually, while the PR I was referring to covers part of the problem, but it is not enough as [this astarte-go code](https://github.com/astarte-platform/astarte-go/blob/0a985dfe94b742c7352c225227e755b6eb5ddca5/client/astarte.go#L362-L365) is not flexible enough to convert all kinds of nested JSON payloads provided by Astarte when `get-samples` is called. 
However, astartectl allows you to add a path to your query. If it is specified  and sufficiently complete, your query will succeed.
