### ISSUE TITLE
Define a standard release cycle and a new versioning scheme

### ISSUE THREAD

**Issue by matt-mazzucato** [astarte-platform/astartectl#163]
A standard release cycle for the Astartectl must be defined.

Given the existing correlation with the Astarte Operator, Astartectl must share both the versioning scheme and the release dates with the Operator. The full specification can be found [here](https://github.com/astarte-platform/astarte-kubernetes-operator/issues/306).

**Comment by Annopaolo** [comment]
Closing after the first release using CalVer (i.e. [v22.11.00](https://github.com/astarte-platform/astartectl/releases/tag/v22.11.00)).
