### ISSUE TITLE
Error on device UUID register

### ISSUE THREAD

**Issue by mc-ff** [astarte-platform/astartectl#182]
Cannot manage a device with UUID starting with '-' char.
Ctl returns :  unknown shorthand flag: '_' in -_cy******************

**Comment by matt-mazzucato** [comment]
If a device ID starts with `-`, you should call the command with a double dash before the device id, e.g.:
```bash
astartectl pairing agent register <your flags> -- <device-id>
```

**Comment by mc-ff** [comment]
That's worked.
