### ISSUE TITLE
`appengine devices data-snapshot`: Not found on existing interface

### ISSUE THREAD

**Issue by rgallor** [astarte-platform/astartectl#195]
Running the `astartectl appengine device data-snapshot` command on a registered device to show the summary of its properties the following error occurred:

```
{
  "errors": {
    "detail": "Not found"
  }
}
```

Looking at the docker-compose logs it seems there is an error in the following HTTP request:

```
astarte-appengine-api_1         | level=info ts=2023-05-12T14:30:02.268+00:00 msg="Got client request." method=GET request_path=/v1/rust/interfaces/org.astarte-platform.rust.examples.individual-properties.ServerProperties module=PlugLoggerWithMeta function=call/2 request_id=F15ro4erGdJN5ToAADlI tag=got_client_req
astarte-appengine-api_1         | level=info ts=2023-05-12T14:30:02.268+00:00 msg="Sent reply." status_code=404 elapsed=163µs module=PlugLoggerWithMeta function=call/2 request_id=F15ro4erGdJN5ToAADlI tag=sent_reply
```

I got the error while trying the astarte-device-sdk-rust running the example individual_properties with the `org.astarte-platform.rust.examples.individual-properties.DeviceProperties` interface

**Comment by matt-mazzucato** [comment]
Closed by #196.
