### ISSUE TITLE
Cannot create realms when explicitly setting a replication strategy

### ISSUE THREAD

**Issue by matt-mazzucato** [astarte-platform/astartectl#214]
After the rework of the astarte-go client (see astarte-platform/astarte-go/issues/33) the creation of a realm is not possible  when a replication strategy is explicitly set. The issue is due to an extra layer of quotes in the json payload which is sent to Astarte.

This behavior affects astartectl v22.11.

**Comment by Annopaolo** [comment]
Closed by #216.
