### ISSUE TITLE
Transmission failures/errors on individual datastreams

### ISSUE THREAD

**Issue by sorru94** [astarte-platform/astartectl#239]
Transmission for individual datastreams sometimes fails or presents incoherent behavior.
The same behavior is present for aggregated datastreams and properties.
The following Astarte types are affected:
- double
- double array
- integer array
- long integer array

### Issue for the double type

The problem arises when sending a double value with its decimal part set at 0. The value is transmitted to the device as an integer instead of a double.

This can be reproduced with the following command using the included interface:
```shell
astartectl appengine --token <TOKEN> --realm-name <REALM NAME> --astarte-url <ASTARTE URL>
    devices send-data <DEVICE ID> org.astarteplatform.examples.ServerDatastream
    /double_endpoint 12.0
```

### Issue for the double array type

The problem is identical to the one for the scalar double described above.

This can be reproduced with the following command using the included interface:
```shell
astartectl appengine --token <TOKEN> --realm-name <REALM NAME> --astarte-url <ASTARTE URL>
    devices send-data <DEVICE ID> org.astarteplatform.examples.ServerDatastream
    /doublearray_endpoint "[12.1, 32.0, 44.2]"
```

### Issue for the integer array type

The problem arises when sending an integer array. The transmission is not performed and the following error is raised:
```
Nested error in integerarray validation: Value float64 for mapping does not match type restrictions for integer
```

This can be reproduced with the following command using the included interface:
```shell
astartectl appengine --token <TOKEN> --realm-name <REALM NAME> --astarte-url <ASTARTE URL>
    devices send-data <DEVICE ID> org.astarteplatform.examples.ServerDatastream
    /integerarray_endpoint "[52, 1]"
```

### Issue for the long integer array type

The problem arises when sending a long integer array. The transmission is not performed and the following error is raised:
```
Internal error in slice processing
```

This can be reproduced with the following command using the included interface:
```shell
astartectl appengine --token <TOKEN> --realm-name <REALM NAME> --astarte-url <ASTARTE URL>
    devices send-data <DEVICE ID> org.astarteplatform.examples.ServerDatastream
    /longintegerarray_endpoint "[17179869185]"
```
[datastream_individual_interface.json](https://github.com/astarte-platform/astartectl/files/14792641/datastream_individual_interface.json)

**Comment by eddbbt** [comment]
First part (double one ) is not an issue with astartectl, but with how astarte handles payload, here is a fix https://github.com/astarte-platform/astarte/pull/921

**Comment by eddbbt** [comment]
third error is handled here https://github.com/astarte-platform/astartectl/pull/240 (works with master, not with current release)

**Comment by eddbbt** [comment]
last one https://github.com/astarte-platform/astarte-go/pull/63

**Comment by eddbbt** [comment]
Actually, points 1 and 2 also occurs with an interface declared as integerArray, for instance 
-> `astartectl appengine devices send-data aXeuCmliToKoyA8Jg6CPCg com.server.Datastream  /testintegerarray "[1, 2]"` 
-> Nested error in integerarray validation: Value float64 for mapping does not match type restrictions for integer

further investigation is needed before deciding if the first pr also fixes this one

**Comment by Annopaolo** [comment]
Closed by https://github.com/astarte-platform/astarte/pull/921, #240, https://github.com/astarte-platform/astarte-go/pull/63
