### ISSUE TITLE
Config commands fail if the base configuration file is not present

### ISSUE THREAD

**Issue by matt-mazzucato** [astarte-platform/astartectl#261]
A number of commands (e.g. `astartectl config contexts list`), under the hood, rely on the retrieval of the `BaseConfigFile`. If that file is not present, the cli returns a cryptic error, i.e.: "file does not exist".

If the config directory is not explicitly set through the command flags **and** the configuration file does not exist, then that file shall be created so that configuration errors are prevented.

The following snippet summarizes both the location and the content of the configuration file:
```bash
cat ~/.config/astarte/astartectl.yaml 
context: ""
```

To fix this issue, the `LoadBaseConfiguration` in `config/base.go` should be modified.

**Comment by eddbbt** [comment]
also ```~/.config/astarte/contexts``` raises an error if directory's not been found, next PR will include also this fix

**Comment by Annopaolo** [comment]
Closed by #262
