### ISSUE TITLE
data-snapshot: Unable to parse Datastream on longpath interface mappings

### ISSUE THREAD

**Issue by fastel** [astarte-platform/astartectl#48]
Astartectl fails to parse datastream if value path is like /%{SensorSN}/%{OutID}/value

Json from appenine API:
{
    "data": {
        "sensorserial1": {
            "output1": {
                "value": {
                    "value": 12341,
                    "timestamp": "2019-11-29T14:27:03.456Z",
                    "reception_timestamp": "2019-11-29T14:27:03.456Z"
                }
            }
        }
    }
}

$ ❯❯❯ astartectl appengine devices data-snapshot grNRc5DGSmCjAZqQs12ipg
Using config file: /Users/___/.astartectl.yaml
Error: Unable to parse Datastream

**Comment by drf** [comment]
Thanks for reporting this.

The issue is not related to the path length, but to a flaky heuristic on the "value" field in the returned JSON, which is always interpreted as the end of an endpoint. So this bug actually affects every path with "value" in a token.
