### ISSUE TITLE
Add support for database_retention_policy and database_retention_ttl

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astartectl#67]
In Astarte 0.11 mappings have two new fields:
- `datatabase_retention_policy`: possible values `"no_ttl"` and `"use_ttl"`, default if not present: `"no_ttl"`.
- `datatabase_retention_ttl`: possible values integers `>= 0`.

Right now `astartectl` does not support them, and since interfaces are deserialized and re-serialized with `astartectl realm-management interfaces install`, the result is that those fields are silently dropped.

**Comment by drf** [comment]
For some reason this wasn't closed. It was fixed by #69 , and it also belongs to astarte-go now.
